<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.6</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>tk.kambaa</groupId>
    <artifactId>technicaldoc-demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name/>
    <description/>
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>
    <properties>
        <java.version>25</java.version>
        <maven.wrapper.executable>${project.basedir}/mvnw.cmd</maven.wrapper.executable>
        <!-- used for exec plugin double/loop run protection-->
        <openapi.docs.exec.running>false</openapi.docs.exec.running>
        <!--
        used for disabling auto-running springdoc-openapi-maven-plugin and
        openapi-generator-maven-plugin (is configured by default)
        -->
        <default.phaserun.skip>true</default.phaserun.skip>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>3.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
            <version>3.0.2</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>org.projectlombok</groupId>
                                    <artifactId>lombok</artifactId>
                                </path>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                    <execution>
                        <id>default-testCompile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                        <configuration>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>org.projectlombok</groupId>
                                    <artifactId>lombok</artifactId>
                                </path>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.5.1</version>

                <executions>
                    <execution>
                        <id>generate-openapi-docs-full</id>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <!-- Prevent recursive execution when the nested mvnw command runs -->
                            <skip>${openapi.docs.exec.running}</skip>
                            <workingDirectory>${project.basedir}</workingDirectory>
                            <executable>${maven.wrapper.executable}</executable>
                            <arguments>
                                <!-- double/run loop protection-->
                                <argument>-Dopenapi.docs.exec.running=true</argument>

                                <!-- by default openapi-generator-maven-plugin and
                                springdoc-openapi-maven-plugin auto-runs on configured maven phases,
                                 so i've configured so that by default they are configured
                                 to be skipped, and only run inside the exec plugin-->
                                <argument>-Ddefault.phase.skip=false</argument>

                                <!--Start spring get the swagger json and stop the app-->
                                <argument>spring-boot:start@start-app</argument>
                                <argument>springdoc-openapi:generate@generate-openapi-json
                                </argument>
                                <argument>spring-boot:stop@stop-app</argument>
                                <!--convert json to asciidoc-->
                                <argument>openapi-generator:generate@generate-openapi-asciidoc
                                </argument>
                                <!-- render HTML from adoc-->
                                <argument>asciidoctor:process-asciidoc@render-technical-html
                                </argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- PLUGINS BELOW ARE USED IN THE EXEC PLUGIN-->
            <!--  GENERATE SWAGGER JSON FILES          -->
            <!--  OPTION 1: USING kbuntrock's openapi-maven-plugin -->
            <!--            <plugin>-->
            <!--                <groupId>io.github.kbuntrock</groupId>-->
            <!--                <artifactId>openapi-maven-plugin</artifactId>-->
            <!--                <version>0.0.31</version>-->
            <!--                <executions>-->
            <!--                    <execution>-->
            <!--                        <phase>compile</phase>-->
            <!--                        <goals>-->
            <!--                            <goal>documentation</goal>-->
            <!--                        </goals>-->
            <!--                    </execution>-->
            <!--                </executions>-->
            <!--                <configuration>-->
            <!--                    <apiConfiguration>-->
            <!--                        <fileFormat>json</fileFormat>-->
            <!--                    </apiConfiguration>-->
            <!--                    <outputDirectory>${project.basedir}/src/main/resources/static</outputDirectory>-->
            <!--                    <filename>swagger.json</filename>-->
            <!--                    <locations>tk.kambaa.technicaldoc.demo.controller</locations>-->
            <!--                </configuration>-->
            <!--            </plugin>-->

            <!-- OPTION 2: GETTING THE SWAGGER JSON FILE FROM RUNTIME (NEED APP STARTUP) -->
            <!--
             start the app, get the swagger json file from /v3/api-docs and save it on resources/static
             run this command:
             ./mvnw clean compile spring-boot:start@start-app springdoc-openapi:generate@generate-openapi-json spring-boot:stop@stop-app
             -->
            <!-- Starts/stops your Spring Boot app manually by execution id -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                    <jvmArguments>
                        -Dspring.application.admin.enabled=true
                        -Dserver.port=8080
                        -Dspringdoc.api-docs.enabled=true
                    </jvmArguments>
                </configuration>

                <executions>
                    <execution>
                        <id>start-app</id>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>

                    <execution>
                        <id>stop-app</id>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Saves runtime /v3/api-docs to swagger.json -->
            <plugin>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-maven-plugin</artifactId>
                <version>1.5</version>
                <executions>
                    <execution>
                        <id>generate-openapi-json</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skip>${default.phaserun.skip}</skip>
                            <apiDocsUrl>http://localhost:8080/v3/api-docs</apiDocsUrl>
                            <outputDir>${project.basedir}/src/main/resources/static</outputDir>
                            <outputFileName>swagger.json</outputFileName>
                            <skip>false</skip>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Generate ASCIIDOC FROM SWAGGER JSON FILE -->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.19.0</version>
                <executions>
                    <execution>
                        <id>generate-openapi-asciidoc</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skip>${default.phaserun.skip}</skip>
                            <!--                            <skip>${skip.docgen}</skip>-->
                            <inputSpec>${project.basedir}/src/main/resources/static/swagger.json
                            </inputSpec>
                            <generatorName>asciidoc</generatorName>
                            <output>${project.basedir}/src/main/resources/static</output>
                            <skipValidateSpec>true</skipValidateSpec>
                            <!--                            <templateDirectory>${openapi.template.en.directory}</templateDirectory>-->
                            <!--                            <configurationFile>${openapi.generator.config.en}</configurationFile>-->
                            <generateSupportingFiles>true</generateSupportingFiles>
                            <supportingFilesToGenerate>index.adoc
                            </supportingFilesToGenerate>
                            <configOptions>
                                <useMethodAndPath>true</useMethodAndPath>
                                <useTableTitles>true</useTableTitles>
                                <appName>OSOS Report Service API</appName>
                                <appDescription>OpenAPI documentation for OSOS report services.
                                </appDescription>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>render-technical-html</id>
                        <!--                                    <phase>process-classes</phase>-->
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                        <configuration>
                            <!--                            <skip>${skip.docgen}</skip>-->
                            <sourceDocumentName>index.adoc</sourceDocumentName>
                            <backend>html5</backend>
                            <sourceDirectory>${project.basedir}/src/main/resources/static
                            </sourceDirectory>
                            <outputDirectory>${project.basedir}/src/main/resources/templates
                            </outputDirectory>
                        </configuration>
                    </execution>

                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>openapi-docs-unix</id>
            <activation>
                <os>
                    <family>unix</family>
                </os>
            </activation>
            <properties>
                <maven.wrapper.executable>${project.basedir}/mvnw</maven.wrapper.executable>
            </properties>
        </profile>

        <profile>
            <id>openapi-docs-windows</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>
            <properties>
                <maven.wrapper.executable>${project.basedir}/mvnw.cmd</maven.wrapper.executable>
            </properties>
        </profile>
    </profiles>

</project>
